# This is a config file containing all the links and sources to fetch data


hacakthon_sources: 
  # https://devfolio.co/hackathons/ 
  # https://devpost.com/hackathons/
    https://devfolio.co/hackathons/open
jobs_sources:

